### PR TITLE
Issue #53: add a parameter to disable updating when robot not moving

### PR DESCRIPTION
**Pull request by corot**

### CODE REVIEW

**Comment by jlblancoc** [comment]
:+1: thanks!

**Comment by corot** [comment]
Can I call your attention to [this comment](https://github.com/mrpt-ros-pkg/mrpt_navigation/pull/54/commits/72f6c6a88506b12a322112da164ddb0d4047b295#diff-7f8e6b816df5e467a097c0bf4d5e71acR240)? Do you think it makes more sense to apply the new flag to EVERY observation?

Thanks, and happy new year!

**Comment by jlblancoc** [comment]
if you mean this one:

> // Robot pose externally provided; update filter regardless update_filter_ flag's value, as these
> // corrections are typically independent from robot motion (e.g. inputs from GPS or tracking system)
> // XXX admittedly an arbitrary choice; feel free to open an issue if you think it doesn't make sense
> 

yes, it makes sense to me to treat GPS or alike in a different way... 👍

**Comment by corot** [comment]
mmmm...  I was considering exactly the opposite: for us the utility of the flag is to keep robot position stable when not moving (that is, when manipulating). But if we break the flag working with GPS or other localization sources...  robot pose will keep changing

**Comment by jlblancoc** [comment]
I think it all depends on how much we trust GPS/... in comparison to PF-based localization :-) 
I had RTK-like GPS in my mind when thinking of GPS.

In any case, we are not using this flag currently in any of our robots, so if you are, and think that it make sense to freeze robot localization from *all* sources, go on and change it. We'll just have to remember explaining the final behavior on ROS wiki...

**Pull request merged**
