### PR TITLE
Backward compatibility fix to PR #30

### PR DESCRIPTION
**Pull request by corot**
Put the ROS log setting withing if MRPT_VERSION>=0x130 so it doesn't break the compilation agains .deb mrpt libs

Also includes a minimal fix to the first mrpt_pose published

### CODE REVIEW

**Comment by jlblancoc** [comment]
Thanks!! However, please set them to `>=0x150` which is the exact minimum version in which that new log system was (is to be) introduced.

**Comment by corot** [comment]
Done!

**Comment by corot** [comment]
Btw, Do you have a new release already scheduled?

**Comment by jlblancoc** [comment]
:+1:  Gracias!!

> Btw, Do you have a new release already scheduled?

Not yet... totally swamped here with other projects! 
But we'll probably release an 1.5.0-beta version within 6-8 weeks, after some work gets finished in the area of reactive navigation.

BTW: What's your experience with this new SLAM packages? :-)

**Comment by corot** [comment]
We only used the localization by now, and is clearly superior to the amcl implementation on ROS navigation. We will probably use other packages in the future.

However, I would take some time to reformat the code. I volunteer to do an automatic ROS-formatting (I have no time for more, sorry), if you want.

**Comment by jlblancoc** [comment]
Good to hear that!

Yes, I would like to see that code reformatting, probably in another PR.
Thanks!

**Pull request merged**
