### PR TITLE
Add mrpt_slam package

### PR DESCRIPTION
**Pull request by nbanyk**
This package uses the mrpt rbpf-slam app as the basis for ROS range-only SLAM. This takes in a rawlog with beacon/odometry data to localize the robot within the mapping of the beacons.  This does not use Lidar data for SLAM.

I can work on the ROS wiki page if this pull request is accepted.

### CODE REVIEW

**Comment by jlblancoc** [comment]
Ey @nbanyk that's a big contribution, thanks! :+1: 

However, I'll ask you to please consider resubmitting the PR against another repo which is intended to hold all MRPT SLAM implementations: https://github.com/mrpt-ros-pkg/mrpt_slam  
so this `mrpt_navigation` repo remains focused on localization and navigation methods, ok? 

Also, the name of your package may be `mrpt_rbpf_slam`, or even `mrpt_ro_slam` if its ROS scope is limited to beacons, don't you think so? 

I'll also CC @Logrus , who has applied to GSoC with MRPT for a project very, very close to what you are working on, so if he eventually got accepted, he needs to be up-to-date with your work there.

**Comment by nbanyk** [comment]
Sure thing, I'll PR it on mrpt_slam - I did not realize that that was an active repository.  Being that there is already a package initially called mrpt_ro_slam, I will call mine mrpt_rbpf_ro_slam so that it is clear what it does.

**Comment by jlblancoc** [comment]
Actually if you take a look at `mrpt_ro_slam` I think it was left blank, so... yours could replace it without problems!

**Comment by nbanyk** [comment]
Ok, I will go with mrpt_ro_slam.

**Pull request closed without merging**
